spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/sample  # Master 설정
      username: sample
      password: password1!
      pool-name: masterDbConnectionPool
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/sample  # Slave 설정(테스트용 같은 DB)
      username: sample
      password: password1!
      pool-name: slaveDbConnectionPool
