# SPRING 설정
spring:
  profiles:
    active: local
    group:
      local: profiles-local
      dev: profiles-dev

---
# AWS 설정
cloud:
  aws:
    region:
      static: ap-northeast-2  # AWS 기본 리전을 설정
    stack:
      auto: false # Spring Cloud를 실행하면, 서버 구성을 자동화하는 CloudFormation이 실행되는데 이를 사용하지 않으므로 false로 설정

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error # 해당 클래스에서 예외가 발생하면 로그를 출력하지 않음

---
# Multipart 설정
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기

---
# LOCAL 설정
spring.config.activate.on-profile: "profiles-local"
spring:
  s3:
    bucket:
    access-key:
    secret-key:

---
# DEV 설정
spring.config.activate.on-profile: "profiles-dev"
spring:
  s3:
    bucket:
    access-key:
    secret-key: